<?php
return [
'cnf_appname' 			=> 'GOJEK API',
'cnf_appdesc' 			=> 'GOJEK API',
'cnf_comname' 			=> 'GOJEK API',
'cnf_email' 			=> 'akbar@solusidata.co.id',
'cnf_metakey' 			=> 'GOJEK API',
'cnf_metadesc' 		=> 'GOJEK API',
'cnf_group' 			=> '3',
'cnf_activation' 		=> 'manual',
'cnf_multilang' 		=> '0',
'cnf_lang' 			=> 'en',
'cnf_regist' 			=> 'false',
'cnf_front' 			=> 'false',
'cnf_recaptcha' 		=> 'false',
'cnf_theme' 			=> 'default',
'cnf_backend' 			=> 'minimal',
'cnf_recaptchapublickey' => '6Le2bjQUAAAAABascn2t0WsRjZbmL6EnxFJUU1H_',
'cnf_recaptchaprivatekey' => '6Le2bjQUAAAAAI6ZKqgzoYS21umpeper74sMK38s',
'cnf_mode' 			=> 'development',
'cnf_logo' 			=> 'backend',
'cnf_allowip' 			=> '',
'cnf_restrictip' 		=> '192.116.134 , 194.111.606.21 ',
'cnf_mail' 			=> 'swift',
'cnf_maps' 			=> 'AIzaSyAayRr-0yZ1ejGGX6l--XDVbHWU85wPj9U',
'cnf_date' 			=> 'Y-m-d',
];
